services:
  stalwart-mail:
    image: stalwartlabs/stalwart:latest
    ports:
      - "443"     # HTTPS
      - "8080"    # HTTP API
      - "25:25"   # SMTP
      - "587:587" # Submission
      - "465"     # SMTPS
      - "143"     # IMAP
      - "993:993" # IMAPS
      - "4190"    # ManageSieve
      - "110"     # POP3
      - "995"     # POP3S
    volumes:
      - stalwart_data:/opt/stalwart-mail
    restart: unless-stopped

  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    volumes:
      - /etc/dokploy/traefik/dynamic/acme.json:/traefik/acme.json:ro
      - /etc/dokploy/traefik/dynamic/certificates:/output
    command: file --watch --source /traefik/acme.json --dest /output
    restart: unless-stopped


volumes:
  stalwart_data:
